#!/usr/bin/env fish

# Automatically generated by Boxen. Don't edit directly. This file
# sets up paths and basic environment for the Boxen dev environment,
# and is intended to be sourced in your shell profile.

# set +e
# set +u

# Make the root of Boxen available.

set -x BOXEN_HOME /opt/boxen

# Add homebrew'd stuff to the path.

set -x PATH $BOXEN_HOME/homebrew/bin $BOXEN_HOME/homebrew/sbin $PATH

# Add homebrew'd stuff to the manpath.

set -x MANPATH $BOXEN_HOME/homebrew/share/man $MANPATH

# Add any binaries specific to Boxen to the path.

set -x PATH $BOXEN_HOME/bin $PATH

###### PARSE ERR: for f in $BOXEN_HOME/env.d/*.sh ; do
###### PARSE ERR:   if [ -f $f ] ; then
###### PARSE ERR:     source $f
###### PARSE ERR:   fi
###### PARSE ERR: done

# Boxen is active.

###### PARSE ERR: if [ -d "$BOXEN_HOME/repo/.git" ]; then
set -x BOXEN_SETUP_VERSION (env GIT_DIR=$BOXEN_HOME/repo/.git git rev-parse --short HEAD)
###### PARSE ERR: else
###### PARSE ERR:   echo "Boxen could not load properly!"
###### PARSE ERR: fi
# Expose basic setup paths. BOXEN_HOME is already exported at the top level.

set -x BOXEN_BIN_DIR /opt/boxen/bin
set -x BOXEN_CONFIG_DIR /opt/boxen/config
set -x BOXEN_DATA_DIR /opt/boxen/data
set -x BOXEN_ENV_DIR /opt/boxen/env.d
set -x BOXEN_LOG_DIR /opt/boxen/log
set -x BOXEN_SOCKET_DIR /opt/boxen/data/project-sockets
set -x BOXEN_SRC_DIR /Users/dbtlr/src
# Expose GitHub credentials

set -x BOXEN_GITHUB_LOGIN dbtlr
set -x HOMEBREW_ROOT /opt/boxen/homebrew
set -x HOMEBREW_CACHE /opt/boxen/cache/homebrew


set -x CFLAGS "-I$HOMEBREW_ROOT/include"
set -x LDFLAGS "-L$HOMEBREW_ROOT/lib"

# Allow bundler to use all the cores for parallel installation
set -x BUNDLE_JOBS 4

# Let the env know where Redis runs.

set -x BOXEN_REDIS_HOST 127.0.0.1
set -x BOXEN_REDIS_PORT 16379

set -x BOXEN_REDIS_URL "redis://$BOXEN_REDIS_HOST $BOXEN_REDIS_PORT/"

set -x BOXEN_MEMCACHED_PORT 21211
set -x BOXEN_MEMCACHED_URL "memcached://127.0.0.1 $BOXEN_MEMCACHED_PORT/"
set -x BOXEN_MONGODB_PORT 17017
set -x BOXEN_MONGODB_URL "mongodb://localhost (BOXEN_MONGODB_PORT)/"
set -x BOXEN_MYSQL_PORT 13306
set -x BOXEN_MYSQL_SOCKET /opt/boxen/data/mysql/socket
set -x BOXEN_MYSQL_URL "mysql://dbtlr@localhost:13306/"

set -x RBENV_ROOT $BOXEN_HOME/rbenv
set -x NODENV_ROOT $BOXEN_HOME/nodenv
set -x PHPENV_ROOT $BOXEN_HOME/phpenv

set -x PATH $BOXEN_HOME/nodenv/shims $BOXEN_HOME/nodenv/bin $PATH
set -x PATH $BOXEN_HOME/phpenv/shims $BOXEN_HOME/phpenv/bin $PATH
set -x PATH $BOXEN_HOME/phpenv/shims $BOXEN_HOME/phpenv/bin $BOXEN_HOME/phpenv/plugins/php-build/bin $PATH
set -x PATH $BOXEN_HOME/rbenv/shims $BOXEN_HOME/rbenv/bin $BOXEN_HOME/rbenv/plugins/ruby-build/bin $PATH
